server:
  port: 7002

spring:
  application:
    name: gateway-zuul2x


  cloud:
    gateway:
      discovery:
        locator:
          enabled:eureka: true
          lower-case-service-id: true
      routes:
        - predicates:
            - Path=/provider-service/**

  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/


